### ISSUE TITLE
Issue installing on OSX 10.12.6

### ISSUE THREAD

**Issue by jrmullins** [tidalcycles/tidal-midi#55]
I successfully brew installed portmidi and then I got this error when trying to cabal install tidal-midi. Any help would be appreciated:

```css-MacBook-Pro:~ cs$ cabal install tidal-midi
Resolving dependencies...
Configuring PortMidi-0.1.6.1...
Building PortMidi-0.1.6.1...
Failed to install PortMidi-0.1.6.1
Build log ( /Users/cs/.cabal/logs/ghc-8.4.2/PortMidi-0.1.6.1-E5rX4IvmqKlAmT1l2rnjO9.log ):
cabal: Entering directory '/var/folders/xc/wppjpqvs1mg_hhb_d1spq92w0000gn/T/cabal-tmp-4735/PortMidi-0.1.6.1'
Configuring PortMidi-0.1.6.1...
Preprocessing library for PortMidi-0.1.6.1..
Building library for PortMidi-0.1.6.1..
[1 of 2] Compiling Sound.PortMidi.DeviceInfo ( dist/build/Sound/PortMidi/DeviceInfo.hs, dist/build/Sound/PortMidi/DeviceInfo.o )
[2 of 2] Compiling Sound.PortMidi   ( Sound/PortMidi.hs, dist/build/Sound/PortMidi.o )
[1 of 2] Compiling Sound.PortMidi.DeviceInfo ( dist/build/Sound/PortMidi/DeviceInfo.hs, dist/build/Sound/PortMidi/DeviceInfo.p_o )
[2 of 2] Compiling Sound.PortMidi   ( Sound/PortMidi.hs, dist/build/Sound/PortMidi.p_o )
In file included from /System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /System/Library/Frameworks/Security.framework/Headers/Security.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:27,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:22,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39,

                 from portmidi/pm_mac/pmmacosxcm.c:38:0: error:

/System/Library/Frameworks/Security.framework/Headers/Authorization.h:192:7: error:
     error: variably modified 'bytes' at file scope
      char bytes[kAuthorizationExternalFormLength];
           ^~~~~
    |
192 |         char bytes[kAuthorizationExternalFormLength];
    |       ^

In file included from portmidi/pm_mac/pmmacosxcm.c:39:0: error:

/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:300:2: error:
     error: expected identifier or '(' before '^' token
     (^MIDINotifyBlock)(const MIDINotification *message);
      ^
    |
300 | (^MIDINotifyBlock)(const MIDINotification *message);
    |  ^

/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:343:2: error:
     error: expected identifier or '(' before '^' token
     (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
      ^
    |
343 | (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
    |  ^

In file included from portmidi/pm_mac/pmmacosxcm.c:39:0: error:

/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1154:6: error:
     error: unknown type name 'MIDINotifyBlock'; did you mean 'MIDINotifyProc'?
          MIDINotifyBlock __nullable notifyBlock )   __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
          ^~~~~~~~~~~~~~~
          MIDINotifyProc
     |
1154 |                                         MIDINotifyBlock __nullable      notifyBlock )                   __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
     |      ^

/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1240:9: error:
     error: unknown type name 'MIDIReadBlock'; did you mean 'MIDIReadProc'?
             MIDIReadBlock readBlock ) __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
             ^~~~~~~~~~~~~
             MIDIReadProc
     |
1240 |                                                                 MIDIReadBlock   readBlock )     __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
     |         ^

/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1643:9: error:
     error: unknown type name 'MIDIReadBlock'; did you mean 'MIDIReadProc'?
             MIDIReadBlock   readBlock ) __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
             ^~~~~~~~~~~~~
             MIDIReadProc
     |
1643 |                                                                 MIDIReadBlock           readBlock ) __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
     |         ^

portmidi/pm_mac/pmmacosxcm.c:60:31: error:
     warning: initialization of 'MIDIClientRef' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
     static MIDIClientRef client = NULL; /* Client handle to the MIDI server */
                                   ^~~~
   |
60 | static MIDIClientRef    client = NULL;  /* Client handle to the MIDI server */
   |                               ^

portmidi/pm_mac/pmmacosxcm.c:61:29: error:
     warning: initialization of 'MIDIPortRef' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
     static MIDIPortRef portIn = NULL; /* Input port handle */
                                 ^~~~
   |
61 | static MIDIPortRef      portIn = NULL;  /* Input port handle */
   |                             ^

portmidi/pm_mac/pmmacosxcm.c:62:30: error:
     warning: initialization of 'MIDIPortRef' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
     static MIDIPortRef portOut = NULL; /* Output port handle */
                                  ^~~~
   |
62 | static MIDIPortRef      portOut = NULL; /* Output port handle */
   |                              ^
portmidi/pm_mac/pmmacosxcm.c: In function 'midi_in_open':

portmidi/pm_mac/pmmacosxcm.c:307:16: error:
     warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         endpoint = (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
                    ^
    |
307 |     endpoint = (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
    |                ^

portmidi/pm_mac/pmmacosxcm.c:308:18: error:
     warning: comparison between pointer and integer
         if (endpoint == NULL) {
                      ^~
    |
308 |     if (endpoint == NULL) {
    |                  ^
portmidi/pm_mac/pmmacosxcm.c: In function 'midi_in_close':

portmidi/pm_mac/pmmacosxcm.c:356:16: error:
     warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         endpoint = (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
                    ^
    |
356 |     endpoint = (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
    |                ^

portmidi/pm_mac/pmmacosxcm.c:357:18: error:
     warning: comparison between pointer and integer
         if (endpoint == NULL) {
                      ^~
    |
357 |     if (endpoint == NULL) {
    |                  ^
portmidi/pm_mac/pmmacosxcm.c: In function 'midi_write_flush':

portmidi/pm_mac/pmmacosxcm.c:431:13: error:
     warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                 (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
                 ^
    |
431 |             (MIDIEndpointRef) descriptors[midi->device_id].descriptor;
    |             ^
portmidi/pm_mac/pmmacosxcm.c: In function 'EndpointName':

portmidi/pm_mac/pmmacosxcm.c:651:26: error:
     warning: initialization of 'MIDIEntityRef' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
       MIDIEntityRef entity = NULL;
                              ^~~~
    |
651 |   MIDIEntityRef entity = NULL;
    |                          ^

portmidi/pm_mac/pmmacosxcm.c:653:14: error:
     warning: comparison between pointer and integer
       if (entity == NULL)
                  ^~
    |
653 |   if (entity == NULL)
    |              ^

portmidi/pm_mac/pmmacosxcm.c:667:26: error:
     warning: initialization of 'MIDIDeviceRef' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
       MIDIDeviceRef device = NULL;
                              ^~~~
    |
667 |   MIDIDeviceRef device = NULL;
    |                          ^

portmidi/pm_mac/pmmacosxcm.c:669:14: error:
     warning: comparison between pointer and integer
       if (device == NULL)
                  ^~
    |
669 |   if (device == NULL)
    |              ^
portmidi/pm_mac/pmmacosxcm.c: In function 'pm_macosxcm_init':

portmidi/pm_mac/pmmacosxcm.c:893:22: error:
     warning: comparison between pointer and integer
             if (endpoint == NULL) {
                          ^~
    |
893 |         if (endpoint == NULL) {
    |                      ^

portmidi/pm_mac/pmmacosxcm.c:903:29: error:
     warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                           TRUE, (void*)endpoint, &pm_macosx_in_dictionary);
                                 ^
    |
903 |                       TRUE, (void*)endpoint, &pm_macosx_in_dictionary);
    |                             ^

portmidi/pm_mac/pmmacosxcm.c:909:22: error:
     warning: comparison between pointer and integer
             if (endpoint == NULL) {
                          ^~
    |
909 |         if (endpoint == NULL) {
    |                      ^

portmidi/pm_mac/pmmacosxcm.c:919:30: error:
     warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                           FALSE, (void*)endpoint, &pm_macosx_out_dictionary);
                                  ^
    |
919 |                       FALSE, (void*)endpoint, &pm_macosx_out_dictionary);
    |                              ^
portmidi/pm_mac/pmmacosxcm.c: In function 'pm_macosxcm_term':

portmidi/pm_mac/pmmacosxcm.c:932:16: error:
     warning: comparison between pointer and integer
         if (client != NULL)  MIDIClientDispose(client);
                    ^~
    |
932 |     if (client != NULL)  MIDIClientDispose(client);
    |                ^

portmidi/pm_mac/pmmacosxcm.c:933:16: error:
     warning: comparison between pointer and integer
         if (portIn != NULL)  MIDIPortDispose(portIn);
                    ^~
    |
933 |     if (portIn != NULL)  MIDIPortDispose(portIn);
    |                ^

portmidi/pm_mac/pmmacosxcm.c:934:17: error:
     warning: comparison between pointer and integer
         if (portOut != NULL) MIDIPortDispose(portOut);
                     ^~
    |
934 |     if (portOut != NULL) MIDIPortDispose(portOut);
    |                 ^
`gcc-8' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/xc/wppjpqvs1mg_hhb_d1spq92w0000gn/T/cabal-tmp-4735/PortMidi-0.1.6.1'
cabal: Error: some packages failed to install:
PortMidi-0.1.6.1-E5rX4IvmqKlAmT1l2rnjO9 failed during the building phase. The
exception was:
ExitFailure 1
tidal-midi-0.9.10-EuwlEzf71yF4GQgzloF1NY depends on tidal-midi-0.9.10 which
failed to install.
```
